- name: Registro Maquina Linux
  hosts: all
  gather_facts: no
  tasks:
    - name: subscription-manager clean
      command: subscription-manager clean
    - name: Register as user (joe_user) auto-subscribe to available content.
      command: subscription-manager register --username alessandro.patricio@200de.com --password Bmgp@2008 --auto-attach
