- name: Register Rhel Subscription Manager
  hosts: all
  gather_facts: no
  tasks:
    - name: subscription-manager clean and unregister
      command: subscription-manager clean
   
    - name: Register as user alessandro auto-subscribe to available content.
      command: subscription-manager register --username "{{sub_username}}" --password "{{sub_password}}" --auto-attach
    
    - name: "Install net-tools packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - net-tools
        
- name: Change hostname Event Drive Ansible
  hosts: 172.20.33.53
  gather_facts: no
  tasks:
    - name: Change hostname Event Drive Ansible
      command: hostname vm-ansible-eda

- name: Change hostname Automation Controller
  hosts: 172.20.33.52
  gather_facts: no
  tasks:
    - name: Change hostname Automation Controller
      command: hostname vm-ansible-automationcontroller

- name: Change hostname Automation Hub
  hosts: 172.20.33.51
  gather_facts: no
  tasks:
    - name: Change hostname Automation Hub
      command: hostname vm-ansible-automationhub

- name: Change hostname db server
  hosts: 172.20.33.54
  gather_facts: no
  tasks:
    - name: Change hostname Database Server
      command: hostname vm-ansible-db

    - name: Remove all Postgres Package
      command: dnf -y remove postgres\*

    - name: Install Repo
      command: dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

    - name: Disable Module
      command: dnf -qy module disable postgresql

    - name: "Install packages"
      command: dnf -y install postgresql15-server
    
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql15-server
    
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/15/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      command: "/usr/pgsql-15/bin/postgresql-15-setup initdb"
    
    - name: Change Default Listen ipaddress
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/15/data/postgresql.conf
        regexp: '^listen_addresses'
        insertafter: '^#listen_addresses'
        line: listen_addresses '*' 
    
    - name: "Change encrption option to postgres"
      lineinfile:
        path: /var/lib/pgsql/15/data/pg_hba.conf
        regexp: "host    all             all             127.0.0.1/32            scram-sha-256" 
        line: "host    all             all             0.0.0.0/0            md5"
        state: present
          
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql-15

    - name: "Create awx database"
      command: sudo -u postgres psql -c 'create database {{db_name}};'
    
    - name: "Create awx user"
      command: sudo -u postgres psql -c "CREATE ROLE {{db_user}} WITH LOGIN SUPERUSER PASSWORD '{{db_password}}';"
