- name: Registro Maquina Linux
  hosts: all
  gather_facts: no
  tasks:
    - name: subscription-manager clean
      command: subscription-manager clean
   # - name: Register as user (joe_user) auto-subscribe to available content.
   #   community.general.redhat_subscription:
   #     state: present
   #     username: alessandro.patricio@200dev.com
   #     password: Bmgp@2008
   #     auto_attach: true
