- name: Playbook para criar inventário do Windows
  hosts: 172.20.33.26
  gather_facts: no

  tasks:
    - name: Find all services that start with 'win'
      ansible.windows.win_service_info:
        name: win*
    
    - name: Obter informações do sistema usando systeminfo
      win_shell: systeminfo
      register: system_info
      changed_when: false

    - name: Get info for a service using its display name
      ansible.windows.win_service_info:
        name: Windows Remote Management (WS-Management)
        register: service_info
    
    - name: Exibir saída do comando Windows Service
      debug:
        var: service_info.stdout    

    - name: Exibir saída do comando systeminfo
      debug:
        var: system_info.stdout
