- name: Playbook para criar inventário do Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Find all services that start with 'Zabbix'
      ansible.windows.win_service_info:
        name: Zabbix Agent
    
    - name: check services
      win_service:
          name: Zabbix Agent
      register: result
      failed_when: result is not defined
      ignore_unreachable: yes
      #ignore_errors: yes
      
    - debug: msg="{{result}}"
    
    - name: Set service Zabbix Agent startup mode to auto and ensure it is started
      win_service:
        name: Zabbix Agent 2 #ssh-agent
        state: stopped

    - name: Configure Zabbix Agent file
      community.windows.win_lineinfile:
        path: C:\Zabbix Agent 2\zabbix_agent2.conf
        regex: '^Server=zabbix.ourinvest.com.br'
        line: 'Server=172.20.32.12'
        regex: '^ServerActive=zabbix.ourinvest.com.br'
        line: 'Server=172.20.32.12'
        regex: '^Hostname=OI-MS-MAP01'
        line: 'Server=172.20.32.12'

    #- name: Configure the Zabbix agent
    #  replace:
    #    path: C:\Zabbix Agent 2\zabbix_agent2.conf
    #    regexp: '{{item.regexp}}'
    #    replace: '{{item.replace}}'
    #  with_items:
    #    - {regexp: "^Server=zabbix.ourinvest.com.br$", replace: "Server={{zabbix_server}}"}
    #    - {regexp: "^ServerActive=zabbix.ourinvest.com.br$", replace: "ServerActive={{zabbix_server}}"}
    #    - {regexp: "^Hostname=OI-MS-MAP01$", replace: "Hostname={{zabbix_server}}"}
    #  vars:
    #    - zabbix_server: 172.20.32.12

    - debug: msg="{{result}}"
      when: result.state is not defined or result.name is not defined
      
    - name: Set service Zabbix Agent startup mode to auto and ensure it is started
      win_service:
        name: Zabbix Agent 2 #ssh-agent
        start_mode: auto
        state: started
   
    #- name: Create a new service to Zabbix Agent
    #  win_service:
    #    name: Zabbix Agent 2
    #    path: C:\Zabbix Agent 2\zabbix_agent2.exe -c C:\Zabbix Agent 2\zabbix_agent2.conf -f=false
    #    display_name: Zabbix Agent Service
    #    description: Zabbix Service Agent
    #  when: result.exists != true

