- name: Playbook para criar inventário do Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Find all services that start with 'Zabbix'
      ansible.windows.win_service_info:
        name: Zabbix Agent
    
    - name: check services
      win_service:
          name: Zabbix Agent
      register: result
      failed_when: result is not defined
      #ignore_errors: yes

    - debug: msg="{{result}}"

    - debug: msg="running"
      when: result.state is not defined or result.name is not defined
 #  - name: Set service Zabbix Agent startup mode to auto and ensure it is started
   #    ansible.windows.win_service:
   #      name: Zabbix Agent #ssh-agent
  #       start_mode: auto
  #       state: started
