- name: Playbook para criar inventário do Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Find all services that start with 'Zabbix'
      ansible.windows.win_service_info:
        name: Zabbix Agent
    
    - name: check services
      win_service:
          name: Zabbix Agent
      register: result
      failed_when: result is not defined
      ignore_unreachable: yes
      #ignore_errors: yes
    - debug: msg="{{result}}"
   
    - name: Create a new service to Zabbix Agent
      win_service:
        name: Zabbix Agent
        path: C:\Zabbix Agent 2\zabbix_agent2.exe -c C:\Zabbix Agent 2\zabbix_agent2.conf -f=false
        display_name: Zabbix Agent Service
        description: Zabbix Serbice Agent
      when: result.exists true

    - debug: msg="{{result}}"
      when: result.state is not defined or result.name is not defined
 #  - name: Set service Zabbix Agent startup mode to auto and ensure it is started
   #    ansible.windows.win_service:
   #      name: Zabbix Agent #ssh-agent
  #       start_mode: auto
  #       state: started
