- name: Playbook para criar inventário do Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Find all services that start with 'Zabbix'
      ansible.windows.win_service_info:
        name: Zabbix Agent
    
    - name: check services
      win_service:
          name: Zabbix Agent
      register: result
      failed_when: result is not defined
      ignore_unreachable: yes
      #ignore_errors: yes
         
    - name: Set service Zabbix Agent startup mode to auto and ensure it is started
      win_service:
        name: Zabbix Agent 2 #ssh-agent
        state: stopped

    - name: Test net
      ignore_errors: yes
      win_wait_for:
        host: gerarcapital.com.br
        port: 443
        timeout: 5
      register: outputnet

    - name: Configure Zabbix Agent file
      community.windows.win_lineinfile:
        path: C:\Zabbix Agent 2\zabbix_agent2.conf
        regex: '^Server=zabbix.ourinvest.com.br'
        line: 'Server=172.20.32.12'
      when: outputnet.failed != true

    - name: Configure Zabbix Agent file - ServerActive
      community.windows.win_lineinfile:
        path: C:\Zabbix Agent 2\zabbix_agent2.conf
        regex: '^ServerActive=zabbix.ourinvest.com.br'
        line: 'ServerActive=172.20.32.12'
      when: outputnet.failed != true
    
    - name: Configure Zabbix Agent file - Hostname
      community.windows.win_lineinfile:
        path: C:\Zabbix Agent 2\zabbix_agent2.conf
        regex: '^Hostname=OI-MS-MAP01'
        line: 'Hostname=SRVTSDEV01'
      when: outputnet.failed != true

    - name: Set service Zabbix Agent startup mode to auto and ensure it is started
      win_service:
        name: Zabbix Agent 2 #ssh-agent
        state: started

    - debug: msg="{{result}}"
    - debug: msg="{{outputnet}}"

