- name: Playbook para criar inventário do Windows
  hosts: 172.20.33.26
  gather_facts: no

  tasks:
    - name: Read CSV File
      read_csv:
        path: users/usuarios.csv
      delegate_to: localhost
      register: users_list

    - name: List users from csv file with users_list variable
      debug:
        msg: "{{ users_list.list }}"
    - name: Print Dictionaries
      debug:
        msg: "{{ item.name }}"
      loop: "{{ users_list.list }}"

    - name: Create Multi User in OU ou=test,dc=200dev,dc=local
      microsoft.ad.user:
        name: "{{ item.name }}"
        password: B0bP4ssw0rd
        path: ou=test,dc=200dev,dc=local
        sam_account_name: "{{ item.sam_account_name }}"
        display_name: "{{ item.display_name }}"
        firstname: "{{ item.firstname }}"
        lastname: "{{ item.lastname }}"
        upn: "{{ item.upn }}"
        groups:
          set:
          - Domain Admins
          - Domain Users
        state: present
      loop: "{{ users_list.list }}"
