- name: Playbook para criar inventário do Windows
  hosts: 172.20.33.26
  gather_facts: no

  tasks:
    - include_vars: users.yml

    - name: Create Multi User in OU ou=test,dc=200dev,dc=local
      microsoft.ad.user:
        name: name={{ item.name }}
        password: {{ item.password }}
        state: present
        path: {{ item.path }}
        groups:
          set:
          - Domain Admins
          - Domain Users
        sam_account_name: {{ item.sam_account_name }}
        display_name: {{ item.display_name }}
        firstname: {{ item.firstname }}
        lastname: {{ item.lastname }}
      with_items: '{{users}}'    
