- name: Playbook para criar inventário do Windows
  hosts: 172.20.33.26
  gather_facts: no

  tasks:
    - name: Find all services that start with 'win'
      ansible.windows.win_service_info:
        name: win*

    - name: Ensure user bob is present in OU ou=test,dc=200dev,dc=local
      microsoft.ad.user:
        name: Alessandro Patricio
        password: {{ password }}
        state: present
        path: ou=test,dc=200dev,dc=local
        groups:
          set:
          - Domain Admins
          - Domain Users
        sam_account_name: aopatricio
        display_name: Alessandro Patricio | 200DEV
        firstname: Alessandro
        lastname: Patricio
        upn: aopatricio@200dev.local
        #domain_username: aopatricio@200dev.local
        #domain_username: 200DEV\aopatricio
        #domain_password: B0bP4ssw0rd
        #domain_server: 200dev@200dev.local
        
