- name: Playbook para criar inventário do Windows
  hosts: 172.20.33.26
  gather_facts: no

  tasks:
    - include_vars: users.yml

    - name: Create Multi User in OU ou=test,dc=200dev,dc=local
      microsoft.ad.user:
        name: name={{ item.name }}
        password: B0bP4ssw0rd
        state: present
        path: name={{ item.path }}
        groups:
          set:
          - Domain Admins
          - Domain Users
        sam_account_name: name={{ item.sam_account_name }}
        display_name: name={{ item.display_name }}
        firstname: name={{ item.firstname }}
        lastname: name={{ item.lastname }}
      with_items: '{{users}}'    
